# Project metadata
project.name=mapnik-java
project.description=Java bindings for Mapnik via a C shim and JNA
project.url=https://github.com/geovannyAvelar/mapnik-java

# Developer information
developer.id=avelar
developer.name=Giovani Avelar
developer.email=github@avelar.dev

org.gradle.parallel=true
org.gradle.caching=true
